homeassistant:  
  auth_providers:
    - type: homeassistant
    - type: trusted_networks
      trusted_networks:
        - 192.168.1.0/24
        - 192.168.2.0/24

  latitude: !secret latitude_home
  longitude: !secret longitude_home
  elevation: 3
  name: Home
  temperature_unit: C
  time_zone: Europe/Dublin
  unit_system: metric



# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
