---
homeassistant:
  auth_providers:
    - type: homeassistant
    - type: trusted_networks
      trusted_networks:
        - 192.168.1.0/24
        - 192.168.10.0/24
  latitude: !secret latitude_home
  longitude: !secret longitude_home
  internal_url: !secret hassio_internal_url
  external_url: !secret hassio_external_url
  elevation: 3
  name: Home
  temperature_unit: C
  time_zone: Europe/Dublin
  unit_system: metric
  currency: GBP

# ipv4:
#   method: manual
#   address: 192.168.1.13/16,192.168.1.1
#   dns: 8.8.8.8;8.8.4.4

config:
default_config:
conversation:
history:
sun:
system_health:

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 192.168.1.0/24

frontend:
  themes: !include_dir_merge_named themes

# Text to speech
tts:
  - platform: google_translate
    service_name: google_say
    cache: true
    cache_dir: /config/tts
    time_memory: 300

mqtt:
  # broker: 127.0.0.1
  # port: 1883
  # discovery: true
  # client_id: home-assistant-1
  # username: !secret mqtt_username
  # password: !secret mqtt_password
  # birth_message:
  #   topic: 'homeassistant/status'
  #   payload: 'online'
  # will_message:
  #   topic: 'homeassistant/status'
  #   payload: 'offline'

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
binary_sensor: !include binary_sensor.yaml
sensor: !include sensors.yaml
